### ISSUE TITLE
decimal point

### ISSUE THREAD

**Issue by ralloss** [Wenlong-Guo/Dimens-Generating#6]
Hi,

there is a bug with the decimal point. It places a "," (comma) instead of  "." dot.
I think it has to do with the default locale.

In my case for example, a value 1.1 is valid but 1,1 is not valid.

Thanks.

**Comment by Wenlong-Guo** [comment]
I forgot use 
`NumberFormat nf = NumberFormat.getNumberInstance（Locale.GERMAN);`
`DecimalFormat的DF =（DecimalFormat的）nf;`
Thank you very much for your issue.
I will fix it in the next version.
